package com.example.demo.infrastructure.spring.fox

import com.google.common.base.Predicates.not
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.context.annotation.Profile
import org.springframework.http.ResponseEntity
import springfox.documentation.builders.PathSelectors.regex
import springfox.documentation.spi.DocumentationType
import springfox.documentation.spring.web.plugins.Docket
import springfox.documentation.swagger2.annotations.EnableSwagger2

@Profile("local")
@Configuration
@EnableSwagger2
class SpringFoxConfig {

    @Bean
    fun document(): Docket {
        return Docket(DocumentationType.SWAGGER_2)
                .select()
                // ignore /error paths which generated by Spring
                .paths(not(regex("/error")))
                .build()
                // delete default response status
                .useDefaultResponseMessages(false)
                // setting to use ResponseEntity
                .genericModelSubstitutes(ResponseEntity::class.java)
    }

}
