version: '3'
services:

  mysql:
    image: mysql:5.7.19
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: demo
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: demo
    #volumes:
    #  - ${PWD}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
