version: '3'
services:

  app:
    image: amazoncorretto:8u202

    ports:
      - 8080:8080
      # TODO リモートデバッグを設定
      #- 5005:5005

    volumes:
      - ${PWD}:/work
      - ~/.gradle:/root/.gradle
    working_dir: /work

    command: >
      ./gradlew
        clean
        flywayMigrate
        generateTablesJooqSchemaSource
        ${GRADLE_COMMAND:-bootRun}

    #-Dspring-boot.run.profiles=local
    #-Drun.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005"

    environment:
      JAVA_HOME: /usr/lib/jvm/java
      APP_ENV: local

      MYSQL_HOST: mysql
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: password

  mysql:
    image: mysql:5.7.19
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: password
