version: '3.5'
services:

  app:
    image: amazoncorretto:8u202

    ports:
      - 8080:8080
      # TODO リモートデバッグを設定
      #- 5005:5005

    volumes:
      - ${PWD}:/work
      - ~/.gradle:/root/.gradle
    working_dir: /work

    command: ./bin/run_locally.sh ${SUB_COMMAND:-develop}

    environment:
      JAVA_HOME: /usr/lib/jvm/java
      APP_ENV: local
      SPRING_PROFILES_ACTIVE: local

      MYSQL_HOST: mysql
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: password

  mysql:
    image: mysql:5.7.19
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: password

networks:
  default:
    name: kotlin-spring-jooq-flyway_default
