version: 2
jobs:
  build:
    machine: true
    working_directory: ~/kotlin-spring-jooq-flyway

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "jooq.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./bin/build_on_docker.sh

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "jooq.gradle" }}

workflows:
  version: 2
  on_commit:
    jobs:
      - build
  cron:
    jobs:
      - build
    triggers:
      - schedule:
          # UTC
          cron: "0 12 * * *"
          filters:
            branches:
              only:
                - master
